[package]
name = "baxter-webservice"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23.0"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
image = { version = "0.24.7", features = ["jpeg", "png"] }
pyo3 = "0.19.2"